from __future__ import annotations

from typing import Final

PROCESSED_CONTRACT_VERSION: Final[str] = "1.0.0"

CSV_ARTIFACT_SPECS: dict[str, set[str]] = {
    "customer_features.csv": {
        "customer_id",
        "segment",
        "channel",
        "recency_days",
        "frequency",
        "monetary",
        "avg_order_value",
        "tenure_days",
        "arpu",
        "is_churned",
        "next_purchase_30d",
    },
    "recommendations.csv": {
        "customer_id",
        "channel",
        "segment",
        "ltv",
        "cac",
        "ltv_cac_ratio",
        "churn_probability",
        "next_purchase_probability",
        "strategic_score",
        "recommended_action",
    },
    "unit_economics.csv": {
        "channel",
        "marketing_spend",
        "customers_acquired",
        "cac",
        "avg_arpu",
        "ltv_cac_ratio",
        "contribution_margin",
        "payback_period_months",
    },
    "top_10_actions.csv": {
        "priority_rank",
        "customer_id",
        "channel",
        "segment",
        "action",
        "strategic_priority_score",
        "expected_uplift",
        "action_cost",
        "net_impact",
        "roi_simulated",
    },
    "cac_by_channel.csv": {
        "channel",
        "marketing_spend",
        "customers_acquired",
        "cac",
    },
    "ltv.csv": {
        "customer_id",
        "channel",
        "segment",
        "ltv",
        "churn_probability",
        "next_purchase_probability",
    },
    "rfm_segments.csv": {
        "customer_id",
        "channel",
        "recency",
        "frequency",
        "monetary",
        "r_score",
        "f_score",
        "m_score",
        "rfm_total",
        "segment",
    },
    "cohort_retention.csv": {
        "cohort_month",
        "cohort_index",
        "active_customers",
        "cohort_size",
        "retention_rate",
    },
}

JSON_ARTIFACT_SPECS: dict[str, tuple[str, ...]] = {
    "quality_report.json": (
        "datasets",
        "total_datasets",
    ),
    "freshness_report.json": (
        "evaluated_at_utc",
        "max_age_hours",
        "status",
        "checks",
    ),
    "raw_input_metadata.json": (
        "generated_at_utc",
        "dataset_count",
        "datasets",
    ),
    "kpi_snapshot.json": (
        "revenue_proxy",
        "avg_arpu",
        "avg_ltv",
        "avg_cac",
        "avg_ltv_cac_ratio",
        "portfolio_size",
        "best_channel_efficiency.channel",
    ),
    "metrics_report.json": (
        "churn.model_name",
        "churn.cv_roc_auc_mean",
        "churn.temporal_test_roc_auc",
        "next_purchase_30d.model_name",
        "next_purchase_30d.cv_roc_auc_mean",
        "next_purchase_30d.temporal_test_roc_auc",
    ),
    "executive_report.json": (
        "data_refresh_utc",
        "base_size.customers_in_scope",
        "base_size.rows_in_recommendation_table",
        "top_kpis.avg_ltv",
        "business_context.revenue_proxy",
        "model_performance.churn",
        "model_performance.next_purchase_30d",
        "recommendations_top_20",
    ),
    "executive_summary.json": (
        "data_refresh_utc",
        "kpis.total_revenue_proxy",
        "kpis.avg_arpu",
        "ltv_cac_by_channel",
        "top_churn_risk_customers",
        "top_20_recommended_actions",
    ),
    "business_outcomes.json": (
        "data_refresh_utc",
        "kpis.avg_ltv_cac_ratio",
        "kpis.simulated_net_impact_top10",
        "simulation_assumptions",
        "simulation_summary_top10.delta_revenue_90d",
        "top_10_actions",
    ),
    "monitoring_report.json": (
        "drift_status",
        "numeric_summary",
        "feature_drift",
        "calibration.churn",
        "calibration.next_purchase_30d",
    ),
    "alerts_report.json": (
        "generated_at_utc",
        "thresholds",
        "alert_count",
        "status",
        "alerts",
    ),
    "semantic_metrics_catalog.json": ("metrics",),
}
